#pragma once


//GUI
#define DARK_CYAN {7, 31, 37}
#define CYAN {9, 77, 94}
#define BRIGHT_CYAN {51, 248, 255}
#define BLACK {0, 0, 0}
#define WHITE {255, 255, 255}

#define ELEMENT_BG_COLOR DARK_CYAN
#define HIGHLIGHT_COLOR CYAN
#define OUTLINE_HIGHLIGHT_COLOR BRIGHT_CYAN
#define BG_COLOR BLACK


#define SPACING 10.f

#define TEXT_COLOR WHITE

#define BUTTON_OUTLINE_WIDTH 2.f
#define BUTTON_BG_COLOR DARK_CYAN
#define BUTTON_PRESS_BG_COLOR HIGHLIGHT_COLOR
#define BUTTON_HOVER_OUTLINE_COLOR OUTLINE_HIGHLIGHT_COLOR
#define BUTTON_SIZE 90.f
#define BUTTON_FONT_SIZE 30.f

#define EXPRESSION_INPUT_BG_COLOR DARK_CYAN
#define EXPRESSION_INPUT_HEIGHT 45.f
#define EXPRESSION_INPUT_FONT_SIZE 35.f


#define FONT "JetBrainsMono-Regular.ttf"

